### ISSUE TITLE
Stuck animations/sounds when casting spells

### ISSUE THREAD

**Issue by arm358** [WowLegacyCore/HermesProxy#104] opened 2022-11-21 13:18 UTC
**Describe the bug**
When casting a spell, sometimes the casting animation (hands glowing) and casting sound will get stuck "on" and not clear. The only fix is a relog (reload does not clear it).
Can be reproduced most easily by spamming Inner Fire (Rank 1). Seems to happen when trying to cast a spell during GCD. 

https://user-images.githubusercontent.com/76705649/203064929-923506bd-e414-4255-ae5b-f6323769a819.mov

**Game Version**
Using Brotalnia's guide for 1.14 client, but launching Arctium through Steam Proton Experimental
Connection to Everlook
![Screenshot from 2022-11-21 07-40-10](https://user-images.githubusercontent.com/76705649/203064995-cb7a10eb-e191-4207-9f81-fa2a6b3770e2.png)

**Hermes Proxy Version**
Latest release for Linux Ubuntu (v3.2 https://github.com/WowLegacyCore/HermesProxy/commit/b0dcbb87248df82c74f95fcb92c9dc67b57c8b52)

**Comment by Lihvar** [comment] 2022-11-23 11:15
This is due to server to proxy(and vice versa) lag/latency. I've added a "fix" for it in my own branch, to induce a manual delay to proxy to avoid this

**Comment by arm358** [comment] 2022-11-23 12:13
thanks - I tried your version but I am getting FAIL_VERSION_INVALID error which I was getting before the latest HermesProxy release. 

Connecting to Everlook

![Screenshot from 2022-11-23 07-13-05](https://user-images.githubusercontent.com/76705649/203544100-14c14cc6-60e6-4331-8ab1-d4db1ed8ff43.png)

**Comment by 0blu** [comment] 2022-11-23 12:21
Is the spell bug also appearing when you toggle the "Optimize for Network speed" option in the game settings?

**Comment by arm358** [comment] 2022-11-23 12:22
Yes -- i have had that option enabled throughout my testing.

**Comment by Lihvar** [comment] 2022-11-23 12:53
I've just updated my version, merging from WoWLegacyCore, you set the delay in the config file, its pretty much testing values and seeing what works, my suggestion is first try 30 for both server and client delay, see how it works, and if it doesn't then I'd suggest increasing Server delay until you find a value that works, its a crude "fix" for a delay in communication between server and the proxy

**Comment by arm358** [comment] 2022-11-23 18:14
> 

Thanks Lihvar - I just downloaded your version (for Ubuntu) and I'm still getting the same "Your version is not supported by this server" error. I do not get that issue when using WoWLegacyCore HermesProxy.

**Comment by arm358** [comment] 2022-11-23 18:14
> I've just updated my version, merging from WoWLegacyCore, you set the delay in the config file, its pretty much testing values and seeing what works, my suggestion is first try 30 for both server and client delay, see how it works, and if it doesn't then I'd suggest increasing Server delay until you find a value that works, its a crude "fix" for a delay in communication between server and the proxy

Thanks Lihvar - I just downloaded your version (for Ubuntu) and I'm still getting the same "Your version is not supported by this server" error. I do not get that issue when using WoWLegacyCore HermesProxy.

**Comment by Lihvar** [comment] 2022-11-23 18:39
I see, tested it myself just now on Everlook and yeah it doesnt accept my fork, its due to versioning and I dont have time to fix that today unfortunately

**Comment by blackcorridors** [comment] 2022-11-26 12:29
Anything on this?
This is a pretty big issue and requires either relogging every time it happens, or playing with no sound as a quasi-fix.

**Comment by Lihvar** [comment] 2022-11-26 15:40
I know, its super annoying, I've updated my version but Everlook only allows the official WoWLegacyCore version

**Comment by blackcorridors** [comment] 2022-11-26 17:34
> I know, its super annoying, I've updated my version but Everlook only allows the official WoWLegacyCore version

Thank you, hopefully the official version gets updated soon with the fix.

**Comment by Lihvar** [comment] 2022-11-27 15:09
It is not real fix I know, but it worked for me, I tried figuring out a real fix and just didn't have the time and expertise.
But the way I can reproduce this 100% of the time is:
- Run SPP(Single Player Project, aka cmangos with bots and the reason behind this is bots which can produce server lag) on a Server PC(separate from Client PC)
- Run HermesProxy from the Server PC as well(NOT CLIENT PC), the settings in Hermes then would be ServerAddress is localhost and ExternalAddress the IP of the Server(in my case 192.168.1.X)
- In SPP settings put like 5000 bots to make sure the server will lag and then just try playing. If I do it like this I get this problem all the time(without artificial delays)

**Comment by 0blu** [comment] 2022-11-27 18:44
Okay my setup looks like this
```
---------------
|    SPP      |              --------------
|   Hermes    | <-- Wifi --> | WoWClassic |
---------------              --------------
```
I set 
```
AiPlayerbot.MinRandomBots = 9000
AiPlayerbot.MaxRandomBots = 9000
```

In game in human start zone I did
```
.learn 588 // Inner Fire
.mod mana 9999999
```
and spammed Inner Fire.

The server was lagging hard, spells and commands took 3 seconds to register.
I was unable to reproduce the bug.

**Comment by Newfriendfromwinter** [comment] 2022-11-27 19:28
Me and my guildmate are also experiencing this issue.  I've had it occur multiple times with the spell Rockbiter Weapon.

**Comment by Lihvar** [comment] 2022-11-27 21:47
How, I get it every single time when the server is lagging and Im even connected via LAN not WiFi. That is super strange

**Comment by Fearyii** [comment] 2022-11-28 12:50
@0blu I am having this issue playing on Everlook as well happends a lot on casts like frost nova or drinking/eating food. I am connected to LAN as well my internet speed is like 120+ mbps so its not an internet issue

**Comment by arm358** [comment] 2022-11-28 13:49
> @0blu I am having this issue playing on Everlook as well happends a lot on casts like frost nova or drinking/eating food. I am connected to LAN as well my internet speed is like 120+ mbps so its not an internet issue

i am in NA and i think it has to do with the ping to the server on France. 1.14 shows 0ms delay between proxy and client but when i load up the 1.12 client directly i get about 120-150ms delay.

**Comment by ratkosrb** [comment] 2022-11-28 13:52
That's cause it shows you ping to the proxy, not to the server, since you are not connected directly to the server. I think Blu made a commit to fix that recently.

**Comment by tronics-glitch** [comment] 2022-11-29 21:58
This is really game/immersion breaking, please fix.

**Comment by MaxtorCoder** [comment] 2022-11-29 21:59
Use latest version of HermesProxy, should be fixed.

**Comment by tronics-glitch** [comment] 2022-11-29 22:00
I just updated and it isn't, that's what made me post

**Comment by 0blu** [comment] 2022-11-29 22:01
You have to go into the `HermesProxy.config` and change it to something like this
```xml
    <add key="ServerSpellDelay" value="50" />
    <add key="ClientSpellDelay" value="50" />
```

**Comment by MaxtorCoder** [comment] 2022-11-29 22:02
Maybe good to assign default values @0blu

**Comment by Lihvar** [comment] 2022-11-29 22:10
I suggest to people trying different values and seeing what works, from personal experience values between 20-80 were good, going over 80 there is gonna be a noticeable delay

**Comment by tronics-glitch** [comment] 2022-11-29 22:10
So this adds latency on purpose to prevent the issue? I already play with like 200ms

**Comment by 0blu** [comment] 2022-11-29 22:11
**Yes**, since we don't know what the real reason for this issue is.
So if you are really keen for DPS you should set it to `0`

**Comment by tronics-glitch** [comment] 2022-11-30 00:37
I put values at 20 and so far I didn't see issue again. Thanks!

**Comment by arm358** [comment] 2022-11-30 14:03
Fixed for me with values at 20 for each variable. Also noticed this made gameplay lag/delay much better as well not just for spells but for shooting wands, fear, etc. Thank you for this!!!!

**Closed** 2022-11-30 14:04 UTC

**Comment by 0blu** [comment] 2022-12-01 02:44
Do you have to set both variables to `20` or is it possible to just set one?
