### ISSUE TITLE
1.14.1 Can't move bullets/arrows into ammo slot

### ISSUE THREAD

**Issue by Daribon** [WowLegacyCore/HermesProxy#211] opened 2022-12-19 01:54 UTC
**Describe the bug**
If you use 1.14.1 and try to move bullets/arrows into ammo slot on your character panel it will never be equipped.
This means that every time you wanna change ammo, you have to use 1.12.1 to equip it.

**Game Server**
VMaNGOS

**Hermes Proxy Version**
![WindowsTerminal_Em8XjSY1SP](https://user-images.githubusercontent.com/6137576/208332884-66faa913-dcda-4c6c-8117-d0e76b6b65a9.png)

**Comment by 0blu** [comment] 2023-01-29 18:04
I tested it on 1.14.1 and I can't reproduce it.
What kind of ammo did you use?

![pic](https://i.imgur.com/pBmOAwA.gif)

**Comment by 0blu** [comment] 2023-01-29 18:45
Might be related to #105

**Comment by ratkosrb** [comment] 2023-01-29 22:23
The opcode was wrong before. It's fixed now.

**Closed** 2023-01-29 22:36 UTC
