### ISSUE TITLE
there was a bug for airplan

### ISSUE THREAD

**Issue by xicyboy** [WowLegacyCore/HermesProxy#190] opened 2022-12-09 13:09 UTC
the airplan undercity to grom'gol ，when i get in the airplan ,i will offline.
video:https://youtu.be/NOGlRBMlSxI

Server:Everlook

HermesProxy Version:3.6

**Comment by ratkosrb** [comment] 2022-12-09 13:58
Duplicate of https://github.com/WowLegacyCore/HermesProxy/issues/88

**Closed by ratkosrb** 2022-12-09 13:58 UTC
