### ISSUE TITLE
Fireball animation keeps casting

### ISSUE THREAD

**Issue by Fearyii** [WowLegacyCore/HermesProxy#116] opened 2022-11-26 19:05 UTC
_Remove all placeholder texts including this message here._

**Describe the bug**
After casting a few fireballs wasnt paying attention i saw my character just having this animation + the sound of the fireball

**Game Server**
Everlook

**Hermes Proxy Version**
 Version 2022-11-25 *official* 3.3.0
![Screenshot_1](https://user-images.githubusercontent.com/111935564/204105124-90a80810-ae1a-41fc-963c-9f536768c5da.png) picture of the animation

on how to recreate i got it from just casting fireball

**Comment by Fearyii** [comment] 2022-11-26 19:06
Edit: after casting fireball again the effect is gone!

**Comment by MaxtorCoder** [comment] 2022-11-26 19:44
Duplicate of #104

**Closed by MaxtorCoder** 2022-11-26 19:44 UTC
